### ISSUE TITLE
Model Performance TIP(S)

### ISSUE THREAD

**Issue by djanibekov** [iamsardorbek/Body-Performace-Data-Analysis#2]
Try to add some optimization techniques for hyper parameter tuning such as `GridSearchCV`, `RandomSearchCV` (they are basic, however, there are some other advanced libs {better to know and not implement rather than being unaware})

**Comment by djanibekov** [comment]
`Oversampling` or `Undersampling` is another optimization technique on data (especially for imbalanced classes). If you decide to try out any, you will need to take into account 'risks'

https://stats.stackexchange.com/questions/234016/opinions-about-oversampling-in-general-and-the-smote-algorithm-in-particular

**Comment by iamsardorbek** [comment]
Implemented RandomSearch, but the computation is taking too long.
I also went through the stackexchange thread you shared. thank you
